rero_mef/authorities/marctojson/do_bnf_auth_person.py
rero_mef/authorities/marctojson/do_gnd_auth_person.py
rero_mef/authorities/marctojson/do_rero_auth_person.py
run-tests.sh
tests/api/conftest.py
tests/authorities/conftest.py
tests/conftest.py
tests/e2e/conftest.py
tests/ui/conftest.py
tests/ui/test_views.py

Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

tests: addition of temporary instance_path

---

rero_mef/authorities/mappings/v6/authorities/bnf-person-v0.0.1.json
rero_mef/authorities/mappings/v6/authorities/gnd-person-v0.0.1.json
rero_mef/authorities/mappings/v6/authorities/mef-person-v0.0.1.json
rero_mef/authorities/mappings/v6/authorities/rero-person-v0.0.1.json
rero_mef/authorities/mappings/v6/authorities/viaf-person-v0.0.1.json

Adds missing _updated and _created properties to es mapping.
Needed for date search!

fix: _updated and _created mappings

---

data/bnf.json
data/gnd.json
data/rero.json
rero_mef/api.py
rero_mef/authorities/jsonschemas/authorities/bnf-person-v0.0.1.json
rero_mef/authorities/jsonschemas/authorities/gnd-person-v0.0.1.json
rero_mef/authorities/jsonschemas/authorities/rero-person-v0.0.1.json
rero_mef/authorities/marctojson/do_bnf_auth_person.py
rero_mef/authorities/marctojson/do_gnd_auth_person.py
rero_mef/authorities/marctojson/do_rero_auth_person.py
rero_mef/authorities/marctojson/helper.py
rero_mef/authorities/minters.py
rero_mef/cli.py
rero_mef/minters.py
tests/authorities/conftest.py
tests/authorities/examples/xml_minimal_record.xml
tests/authorities/test_bnf_auth_person.py
tests/authorities/test_gnd_auth_person.py
tests/authorities/test_ref_resolver.py
tests/authorities/test_rero_auth_person.py

Signed-off-by: Gianni Pante <gianni.pante@rero.ch>
Co-author : Nicolas Labat <nicolas.labat@rero.ch>
Co-author : Aly Badr <aly.badr@rero.ch>
To test:
pip install -e .[all]
./scripts/bootstrap
./scripts/setup
./run-tests
Display the sources (bnf, gnd, rero) records:
http://localhost:5000/api/bnf/?q=&prettyprint=1&size=100
http://localhost:5000/api/gnd/?q=&prettyprint=1&size=100
http://localhost:5000/api/rero/?q=&prettyprint=1&size=100
and make sure the identifier of person field is a URI

feat: implement the additional transformation

---

rero_mef/authorities/marctojson/do_bnf_auth_person.py
rero_mef/cli.py
scripts/setup

* FIX: closes #11, closes #12
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
Co-Authored-by: Nicolas Labat <nicolas.labat@rero.ch>
To test:
- get the PR branch
- run the tests
- re-generate the BNF json file from marc_file using this command
AGENCY=bnf
INPUT_DIR=/Volumes/documents/documentation/projets/RERO21/metadata/personne/bulk_full_data
OUTPUT_DIR=data
pipenv run invenio records bulk_load ${AGENCY} ${INPUT_DIR} ${OUTPUT_DIR} --marc_file ${AGENCY}.mrc --json_file ${AGENCY}.json
- After generating the file, make sure in the bnf json file you do not have records without author
grep -v "preferred_name_for_person" data/bnf_metadata.csv |wc -l
results should equal to 0

Data Load: eleminate records without author person

---

Pipfile.lock
deployment/kubernetes/indexer.yaml
deployment/mef-services.yaml
rero_mef/config.py
rero_mef/serializers.py
run-tests.sh

test:
http://localhost:5002/api/mef/3?prettyprint=1&
http://localhost:5002/api/mef/3?prettyprint=1&resolve=1

Ref serializer

---

rero_mef/authorities/marctojson/do_bnf_auth_person.py
rero_mef/authorities/marctojson/do_gnd_auth_person.py
rero_mef/authorities/marctojson/do_rero_auth_person.py
scripts/setup

* BETTER: added numbers to prefered name
Signed-off-by: Peter Weber <Peter.Weber@rero.ch>

DATA: numbers in prefered name

---

README.rst

* BETTER Corrects the links on the README file.
Signed-off-by: Igor Milhit <igor.milhit@rero.ch>

documentation: actual links in the README file

---

poetry.lock
rero_mef/agents/gnd/tasks.py
rero_mef/agents/idref/tasks.py
rero_mef/cli.py
rero_mef/utils.py

* We don't need any more the MyOaiItemIterator, because the OaiItemIterator from sickle had some improvements.
* Adds functionality to get VIAF online during OAI harvesting.

oai: harvesting

---

CHANGES.md
RELEASE-NOTES.md
pyproject.toml
rero_mef/version.py

Co-Authored-by: Igor Milhit <igor.milhit@rero.ch>
release commit

release: v0.7.0

---

poetry.lock
pyproject.toml
rero_mef/agents/api.py
rero_mef/agents/gnd/tasks.py
rero_mef/agents/idref/tasks.py
rero_mef/cli.py
rero_mef/utils.py

* Uses a more error resistent OAIItemIterator for harvesting.

harvester: use MyOAIItemIterator

---

.github/workflows/continuous-integration-test.yml
Dockerfile
Dockerfile.base
INSTALL.rst
poetry.lock
pyproject.toml
run-tests.sh
scripts/bootstrap
setup.py

* Uses poetry >= 1.1.
* Uses latest invenio packages.

deployment: use new poetry

---

.github/workflows/continuous-integration-test.yml
Dockerfile.base
poetry.lock
pyproject.toml
tests/conftest.py

* Updates python packages.
* Updates github action script.

deployment: update

---

poetry.lock
rero_mef/agents/cli.py
rero_mef/agents/mef/api.py
rero_mef/agents/tasks.py
rero_mef/api.py
rero_mef/api_mef.py
rero_mef/cli.py
rero_mef/marctojson/do_idref_agent.py
rero_mef/monitoring.py
rero_mef/query.py
rero_mef/tasks.py
tests/unit/agents/test_agent_idref_transformation.py

* Closes https://github.com/rero/rero-ils/issues/2559
* Takes the transliterated form instead of original script in
authorised access point

authorized access points

---

rero_mef/agents/api.py
rero_mef/agents/mef/api.py
rero_mef/agents/tasks.py
rero_mef/api.py
rero_mef/api_mef.py
rero_mef/config.py
rero_mef/filter.py
rero_mef/query.py
rero_mef/tasks.py
rero_mef/utils.py
tests/api/test_view_agents_mef.py
tests/unit/test_api.py

* Deleted enteties could be accessed by MEF.

MEF: fix deleted agents

---

CHANGELOG.md
pyproject.toml
rero_mef/version.py

Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

release: v0.9.0

---

rero_mef/marctojson/do_idref_agent.py

dojson: fix script code

---

poetry.lock
pyproject.toml
rero_mef/theme/templates/rero_mef/footer.html
rero_mef/theme/templates/rero_mef/frontpage.html

* Update footer and front page links
* Update dependencies
Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

templates: update footer and front page links

---

rero_mef/api.py
rero_mef/utils.py

* Eliminates exceptions for bulk indexing.
* Better code with sourcery suggestions.

indexer: better code

---

rero_mef/cli.py
rero_mef/marctojson/do_idref_agent.py
rero_mef/utils.py
tests/unit/agents/test_agent_idref_transformation.py
tests/unit/agents/test_idref_contributions_person.py
tests/unit/test_marctojson_helper.py

dojson: fix parentheses with spaces

---

poetry.lock

dependencies: update the dependencies lock file

---

pyproject.toml
rero_mef/alembic/c658fa8e9fa5_inital_branch.py

alembic: inital branch

---

rero_mef/concepts/cli.py

concepts: fix create_mef

---

rero_mef/agents/__init__.py
rero_mef/api.py
rero_mef/concepts/__init__.py
rero_mef/concepts/rero/jsonschemas/concepts_rero/rero-concept-v0.0.1.json
tests/api/test_agents_gnd_rest.py

entities: save old date if deleted

---

rero_mef/agents/mef/api.py
rero_mef/utils.py
tests/api/test_agents_mef_rest.py
tests/api/test_concepts_mef_rest.py

* Uses `scan` in `generator` function to generate a complete result.

api: fix updated

---

CHANGELOG.md
pyproject.toml
rero_mef/version.py

Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

release: v0.10.0

---

rero_mef/views.py

* Corrects /api/idref/PID to /api/agents/idref/PID redirection.

idref: fix agent IdRef redirection

---

.github/workflows/continuous-integration-test.yml
poetry.lock
pyproject.toml
rero_mef/agents/mef/api.py
rero_mef/api_mef.py
rero_mef/concepts/mef/api.py
rero_mef/utils.py
run-tests.sh
tests/api/test_agents_mef_rest.py

* Adds `resolve` to POST parameter.
* Without `resolve` only `pid`, `_created`, `_updated` and `deleted`` will be returned.
* Are unknown pids will be reported back without additional information. Example `{'pid', '42'}

agents, concepts: better changed api

---

rero_mef/agents/gnd/tasks.py
rero_mef/agents/rero/tasks.py
rero_mef/agents/viaf/api.py
rero_mef/config.py
rero_mef/utils.py
tests/ui/agents/test_agents_viaf_api.py
tests/ui/test_oai.py

* Adds request retry session function.
* Uses SRU service to download GND records.

agents GND: Get online record by SRU

---

poetry.lock
rero_mef/agents/api.py
rero_mef/agents/mef/api.py
rero_mef/agents/mef/mappings/v7/mef/mef-v0.0.1.json
rero_mef/agents/viaf/api.py
rero_mef/api.py
rero_mef/api_mef.py
rero_mef/cli.py
rero_mef/concepts/api.py
rero_mef/concepts/mef/api.py
rero_mef/tasks.py
rero_mef/utils.py
tests/ui/agents/test_agents_api.py
tests/ui/agents/test_agents_api_no_viaf.py
tests/ui/agents/test_agents_viaf_api.py
tests/ui/agents/test_signals.py
tests/ui/concepts/test_concepts_api.py
tests/ui/test_mef.py
tests/ui/test_oai.py

* Fixes problems during VIAF updates.   
* Dependencies updates

viaf: fix update 

---

CHANGELOG.md
poetry.lock
pyproject.toml

dependencies: fix security issues

---

poetry.lock
rero_mef/concepts/mef/api.py
rero_mef/utils.py
tests/ui/concepts/test_concepts_api.py

* Corrects MEF type for concept type changes.
* Dependencies update.
* Corrects harvesting dates calculation.

concepts: correct type

---

CHANGELOG.md
poetry.lock
pyproject.toml
rero_mef/version.py

release: v0.16.1

---

poetry.lock
pyproject.toml
rero_mef/api.py
rero_mef/concepts/gnd/api.py
rero_mef/concepts/idref/api.py
rero_mef/config.py
scripts/test
tests/ui/concepts/test_concepts_api.py

* Creates MEF records for GND records if there are one extra match and close matches in other GND records.
* Closes #rero-ils/3827
* dependencies update

concepts: MEF creation for one exact match
